def add_step(steps, priority, action, reason):
    """
    Add a solve step while avoiding duplicate actions.
    """

    for step in steps:
        if step["action"] == action:
            return

    steps.append(
        {
            "priority": priority,
            "action": action,
            "reason": reason
        }
    )


def generate_solve_plan(
    file_type,
    findings,
    detected_flags=None,
    encoding_results=None,
    archive_results=None,
    classification_result=None
):
    """
    Build an intelligent CTF solve plan from analysis results.

    The planner does not execute offensive actions.
    It analyzes FalconCTF findings and decides what the analyst
    should investigate next.

    Parameters:
        file_type:
            File type detected by FalconCTF.

        findings:
            Interesting findings collected during analysis.

        detected_flags:
            Flag candidates detected during analysis.

        encoding_results:
            Base64, hex and recursive encoding results.

        archive_results:
            Archive inspection results.

        classification_result:
            Challenge classification generated by FalconCTF.

    Returns:
        A list of prioritized solve steps.
    """

    detected_flags = detected_flags or []
    encoding_results = encoding_results or {}
    archive_results = archive_results or {}
    classification_result = classification_result or {}

    steps = []

    # -------------------------------------------------
    # Normalize important values
    # -------------------------------------------------

    file_type_lower = str(file_type).strip().lower()

    challenge_category = str(
        classification_result.get(
            "category",
            ""
        )
    ).strip().lower()

    # -------------------------------------------------
    # Highest priority: flag already detected
    # -------------------------------------------------

    if detected_flags:
        add_step(
            steps,
            100,
            "Verify the detected flag candidate.",
            "One or more flag-like strings were already detected."
        )

    # -------------------------------------------------
    # Encoding intelligence
    # -------------------------------------------------

    if findings.get("base64_decoded"):
        add_step(
            steps,
            90,
            "Inspect the decoded Base64 content.",
            "Base64 data was successfully decoded and may reveal "
            "another layer of the challenge."
        )

    if findings.get("hex_decoded"):
        add_step(
            steps,
            90,
            "Inspect the decoded hexadecimal content.",
            "Hex-encoded data was successfully decoded and may "
            "contain useful challenge information."
        )

    recursive_layers = encoding_results.get(
        "recursive_layers",
        []
    )

    if recursive_layers:
        maximum_depth = max(
            (
                layer.get("depth", 0)
                for layer in recursive_layers
            ),
            default=0
        )

        if maximum_depth > 1:
            add_step(
                steps,
                92,
                "Follow the recursive encoding chain to its final layer.",
                (
                    "Multiple encoding layers were detected "
                    f"with a maximum depth of {maximum_depth}."
                )
            )

    # -------------------------------------------------
    # Decoded Payload Intelligence
    # -------------------------------------------------

    decoded_payloads = encoding_results.get(
        "payloads",
        []
    )

    for payload in decoded_payloads:
        payload_route = str(
            payload.get(
                "route",
                ""
            )
        ).lower()

        payload_type = str(
            payload.get(
                "payload_type",
                "Unknown Payload"
            )
        )

        source_encoding = str(
            payload.get(
                "source_encoding",
                "encoded data"
            )
        ).upper()

        confidence = payload.get(
            "confidence",
            0
        )

        if payload_route == "archive_analysis":
            add_step(
                steps,
                95,
                "Analyze the decoded archive payload.",
                (
                    f"{source_encoding} decoding revealed "
                    f"{payload_type} with {confidence}% confidence."
                )
            )

        elif payload_route == "binary_analysis":
            add_step(
                steps,
                95,
                "Perform static analysis on the decoded executable payload.",
                (
                    f"{source_encoding} decoding revealed "
                    f"{payload_type} with {confidence}% confidence."
                )
            )

        elif payload_route == "forensics":
            add_step(
                steps,
                90,
                "Inspect the decoded forensic payload.",
                (
                    f"{source_encoding} decoding revealed "
                    f"{payload_type} with {confidence}% confidence."
                )
            )

        elif payload_route == "encoding_analysis":
            add_step(
                steps,
                88,
                "Continue analyzing the decoded encoding layer.",
                (
                    f"{source_encoding} decoding revealed "
                    "another encoded payload."
                )
            )

        elif payload_route == "verify_flag":
            add_step(
                steps,
                100,
                "Verify the flag recovered from the decoded payload.",
                (
                    f"{source_encoding} decoding revealed "
                    "a flag-like payload."
                )
            )

    # -------------------------------------------------
    # Archive intelligence
    # -------------------------------------------------

    encrypted_files = archive_results.get(
        "encrypted_files",
        []
    )

    decrypted_files = archive_results.get(
        "decrypted_files",
        []
    )

    interesting_archive_files = archive_results.get(
        "interesting_files",
        []
    )

    if encrypted_files and not decrypted_files:
        add_step(
            steps,
            85,
            "Investigate the encrypted archive contents.",
            "Protected files were detected and may hide important "
            "challenge data."
        )

    if decrypted_files:
        add_step(
            steps,
            88,
            "Inspect the successfully decrypted files.",
            "Protected archive content was successfully opened."
        )

    if interesting_archive_files:
        add_step(
            steps,
            80,
            "Inspect interesting files discovered inside the archive.",
            "Archive filenames or extensions indicate potentially "
            "important challenge content."
        )

    # -------------------------------------------------
    # Interesting strings
    # -------------------------------------------------

    if findings.get("keywords"):
        add_step(
            steps,
            75,
            "Review sensitive or interesting keywords.",
            "Keywords related to flags, passwords, keys, tokens, "
            "or credentials were detected."
        )

    if findings.get("urls"):
        add_step(
            steps,
            65,
            "Review discovered URLs for challenge context.",
            "URLs may reference additional challenge resources "
            "or hidden information."
        )

    if findings.get("emails"):
        add_step(
            steps,
            55,
            "Review discovered email addresses.",
            "Email addresses may provide useful challenge context."
        )

    if findings.get("ips"):
        add_step(
            steps,
            55,
            "Review discovered IP addresses.",
            "IP addresses may be relevant to the challenge."
        )

    # -------------------------------------------------
    # Challenge classification intelligence
    # -------------------------------------------------

    if (
        "encoding" in challenge_category
        or "crypto" in challenge_category
    ):
        add_step(
            steps,
            82,
            "Prioritize decoding and transformation analysis.",
            "FalconCTF classified the challenge as Encoding / Crypto."
        )

    if "forensic" in challenge_category:
        add_step(
            steps,
            82,
            "Prioritize forensic artifact inspection.",
            "FalconCTF classified the challenge as Forensics."
        )

    if (
        "reverse" in challenge_category
        or "reversing" in challenge_category
    ):
        add_step(
            steps,
            82,
            "Prioritize static reverse engineering.",
            "FalconCTF classified the challenge as Reverse Engineering."
        )

    if "pwn" in challenge_category:
        add_step(
            steps,
            82,
            "Inspect binary protections and program behavior.",
            "FalconCTF classified the challenge as Pwn."
        )

    if "web" in challenge_category:
        add_step(
            steps,
            82,
            "Review the web challenge attack surface.",
            "FalconCTF classified the challenge as Web."
        )

    if "osint" in challenge_category:
        add_step(
            steps,
            82,
            "Correlate discovered public information.",
            "FalconCTF classified the challenge as OSINT."
        )

    # -------------------------------------------------
    # File-type intelligence
    # -------------------------------------------------

    if "gzip" in file_type_lower:
        add_step(
            steps,
            75,
            "Continue analysis of the extracted GZIP payload.",
            (
                "The target is a GZIP-compressed container. "
                "The extracted inner payload should drive "
                "the next analysis stage."
            )
        )

    elif "zip" in file_type_lower:
        add_step(
            steps,
            70,
            "Inspect the archive structure and nested files.",
            "The target appears to be a ZIP archive."
        )

    is_executable = any(
        indicator in file_type_lower
        for indicator in (
            "elf executable",
            "elf 32-bit",
            "elf 64-bit",
            "pe32 executable",
            "pe32+ executable",
            "ms-dos executable",
            "mach-o executable"
        )
    )

    if is_executable:
        add_step(
            steps,
            70,
            "Perform deeper static analysis of the executable.",
            "The detected file type indicates executable code."
        )

    is_image = any(
        indicator in file_type_lower
        for indicator in (
            "png image",
            "jpeg image",
            "jpg image",
            "gif image",
            "bitmap image",
            "webp image"
        )
    )

    if is_image:
        add_step(
            steps,
            60,
            "Inspect image metadata and hidden-data indicators.",
            "The target appears to be an image-based challenge artifact."
        )

    # -------------------------------------------------
    # No flag yet
    # -------------------------------------------------

    if not detected_flags and recursive_layers:
        add_step(
            steps,
            78,
            "Inspect the final decoded payload for a flag or new format.",
            "The recursive decoding process completed without "
            "detecting a confirmed flag."
        )

    # -------------------------------------------------
    # Fallback
    # -------------------------------------------------

    if not steps:
        add_step(
            steps,
            10,
            "Perform manual inspection of the file and extracted strings.",
            "No strong automatic solve path was identified."
        )

    # -------------------------------------------------
    # Sort by priority
    # -------------------------------------------------

    steps.sort(
        key=lambda item: item["priority"],
        reverse=True
    )

    return steps


def print_solve_plan(steps):
    """
    Display the generated solve plan.
    """

    print("\n" + "=" * 55)
    print("FalconCTF Intelligent Solve Plan")
    print("=" * 55)

    if not steps:
        print(
            "\nNo solve-plan steps were generated."
        )
        return

    for index, step in enumerate(
        steps,
        start=1
    ):
        print(
            f"\n[{index}] {step['action']}"
        )

        print(
            f"    Priority : {step['priority']}"
        )

        print(
            f"    Reason   : {step['reason']}"
        )
